CREATE TABLE Party (
PartyID			INT PRIMARY KEY IDENTITY (1,1),
PartySize		TINYINT			NOT NULL,
Adults			TINYINT			NOT NULL,
Children		TINYINT			NOT NULL,
Pets			TINYINT			NOT NULL,
GuestID			INT	REFERENCES  LeadGuest(GuestID)
					ON DELETE NO ACTION
);
